name: histopathTDA-contributing
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - bandit
  - benchmark
  - coverage
  - flake8
  - mypy
  - pygal
  - pyroma
  - pytest
  - python==3.7
  - nbformat
  - ripser
  - jupyter_client
  - ipykernel
  - pip
  - pip:
    - pip
    - torch==1.3.1
    - tqdm>=4.35.0
    - pandas>=0.24.2
    - matplotlib>=3.1.1
    - h5py>=2.9.0
    - scikit-learn>=0.22
    - seaborn>=0.9.0
    - torchvision==0.4.2
    - pillow==6.2.2
    - opencv-python==4.5.4.60
    - scikit-image==0.17.2
    - dgl==0.4.3.post2
    - PyYAML>=5.1.2
    - giotto-tda
    - histocartography
    - prospector[with_pyroma, with_vulture, with_frosted, with_bandit, with_mypy]
    - pygaljs
    - pytest-benchmark
    - PersistenceImages
    - pytest-cov
    - tox-conda
    - tox
    - Sphinx
    - histocartography
    - POT
    - cython
    - numpy==1.21.4
    - gudhi
